### ISSUE TITLE
apache version check

### ISSUE THREAD

**Issue by skurudo** [petranikin/mgrvphp#2]
Hi, 

When you get templates, I think, you need apache version too. What's point? It is in **IncludeOptional** and Include directives. **IncludeOptional** for apache > 2.4 (2.3.6 more precisely), but **Include** for apache < 2.4. **IncludeOptional** do not work with apache 2.2

I see there is two options:
- two sets of tpl(s) files for new and for old apache
- download same files as now, but then make check if apache version lower than 2.3.6, parse those. Like this for example: 
`find /usr/local/vesta/data/templates/web/apache2/ -type f -name "*.*tpl" | xargs sed -i 's/IncludeOptional/Include/g' `

...

Привет, думаю, имеет смысл проверять версию apache при скачивании темплейтов. Все из-за того, что опции **IncludeOptional** и **Include** работают для разных версий apache. **IncludeOptional** для старших версий вроде 2.4 (точнее 2.3.6 и выше), но не работают на нижних версиях, как 2.2 к примеру, так как для них подходит только **Include**

Я вижу здесь два пути:
- сделать два набора темплейтов (здесь просто копипаста) - при проверке версии apache скачивается нужный набор;
- скачивать и устанавливать как сейчас, но после этого проверять версию apache и если она ниже 2.3.6 делать замену  **IncludeOptional** на **Include**, например вот так:
`find /usr/local/vesta/data/templates/web/apache2/ -type f -name "*.*tpl" | xargs sed -i 's/IncludeOptional/Include/g' `

**Comment by petranikin** [comment]
Привет. Ага. Сделаю в ближайший коммит.

**Comment by petranikin** [comment]
Готово
